# Historical Weather Data API
https://historical-forecast-api.open-meteo.com/v1/forecast?latitude=42.3829916&longitude=-72.4570739&start_date=2024-11-03&end_date=2024-11-16&hourly=temperature_2m,relative_humidity_2m,precipitation,snow_depth,weather_code,cloud_cover,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,soil_temperature_0cm,soil_temperature_6cm,soil_temperature_18cm,soil_temperature_54cm,soil_moisture_0_to_1cm,soil_moisture_1_to_3cm,soil_moisture_3_to_9cm,soil_moisture_9_to_27cm,soil_moisture_27_to_81cm&timezone=America%2FNew_York

###

# Forecast Weather Data API
https://api.open-meteo.com/v1/forecast?latitude=42.3829916&longitude=-72.4570739&hourly=temperature_2m,relative_humidity_2m,dew_point_2m,precipitation,weathercode,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,soil_temperature_0cm,soil_temperature_6cm,soil_temperature_18cm,soil_temperature_54cm,soil_moisture_0_to_1cm,soil_moisture_1_to_3cm,soil_moisture_3_to_9cm,soil_moisture_9_to_27cm,soil_moisture_27_to_81cm&past_days=2&timezone=auto

###

# debug 

https://api.open-meteo.com/v1/forecast?latitude=42.3829916&longitude=-72.4570739&hourly=temperature_2m,relative_humidity_2m,dew_point_2m,precipitation,weather_code,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,soil_temperature_0cm,soil_temperature_6cm,soil_temperature_18cm,soil_temperature_54cm,soil_moisture_0_to_1cm,soil_moisture_1_to_3cm,soil_moisture_3_to_9cm,soil_moisture_9_to_27cm,soil_moisture_27_to_81cm&past_days=1&timezone=auto
